import type { Metadata } from 'next';
import './globals.css';
import React from 'react';
import { montserrat } from '@/app/fonts/google';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body className={montserrat.className}>{children}</body>
		</html>
	);
}
